### PR TITLE
readme: Added table of contents

### PR DESCRIPTION
**Pull request by 4kills**

### CODE REVIEW

**Comment by ebiggers** [comment]
Looks good, but can you please squash your two commits into one?

**Comment by 4kills** [comment]
Hey thanks! Next to the "Merge Pull Request" there is a drop-down menu where you can select "squash and merge" and that should squash my two commits for a clean commit history in your project :) 
If the option isn't there for some reason, I can squash the commits first and then create a pull request.

**Comment by ebiggers** [comment]
It's the job of the person opening the pull request to create a clean commit (or series of commits) with proper commit messages.

There's no need to create a new pull request; just rebase and force-push to your branch.

**Comment by 4kills** [comment]
Sure - done

**Comment by ebiggers** [comment]
Merged, thanks!

**Pull request merged**
