### PR TITLE
Use _target_attribute instead of __attribute__((target(t)))

### PR DESCRIPTION
**Pull request by pps83**

### CODE REVIEW

**Review by ebiggers — COMMENTED** [review]
I guess this is okay.  Another way to do it would be make the non-empty definitions of `ATTRIBUTES` conditional on `!defined(_MSC_VER)`, or on something like `!HAVE_INTRIN_WITHOUT_TARGET`.  Your way is a bit more concise, but makes it a bit less clear what is going on (it could be unexpected that the target is ignored). Can you add a comment above `_target_attribute` that makes it super clear why an empty definition is used with MSVC?

**Comment by pps83** [comment]
> Can you add a comment above `_target_attribute` that makes it super clear why an empty definition is used with MSVC?

can you pleases write, I'll just copy paste to avoid doing back-forth with edits

**Comment by pps83** [comment]
added comment/description

**Comment by pps83** [comment]
FYI, this is relevant to the commit: https://github.com/ebiggers/libdeflate/issues/219#issuecomment-1326386205

**Comment by ebiggers** [comment]
Merged, thanks.

**Pull request merged**
