### PR TITLE
scripts/gen_crc32_multipliers.c: remove unused format string argument

### PR DESCRIPTION
**Pull request by gemesa**

### CODE REVIEW

**Comment by ebiggers** [comment]
> fix: remove unused format string argument

For future reference, the prefix is supposed to be the component modified (e.g. `scripts`), not the type of change (e.g. `fix`).

**Comment by gemesa** [comment]
Noted, should I rename it with a force push?

**Comment by ebiggers** [comment]
Sure, please do.

**Comment by ebiggers** [comment]
Merged, thanks.

**Pull request merged**
